name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: ['*']

jobs:
  build:

    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: |
          npm install
          (cd test/old && npm install)
          (cd test/flat && npm install)
          (cd test/flat-module && npm install)
      - name: Check coding standards
        run: npm run lint
      - name: Test
        run: npm run test
